
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author root
 */


public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    
    private client c;
    private static gui GUI =null;
    
    
    private Frame1 F1;
    private Frame2 F2;
    private Frame3 F3;
    private Frame4 F4;
    private Frame5 F5;
    
    private gui() throws IOException 
    {
        initComponents();
        
        c = new client("localhost",1002);
        
        
        F1 = new Frame1();
        F2 = new Frame2();
        F3 = new Frame3();
        F4 = new Frame4();
        F5 = new Frame5();
        
        F5.setVisible(true);
        c.connect();
    }
    public static gui GetInstance() throws IOException
    {
        if(GUI == null)
            GUI = new gui();
        
        return GUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


   
    public void LogForm()
    {
        F1.setVisible(true);
    }
    public void PublicChatForm() throws IOException
    {
        F2.setVisible(true);
    }
    public void MainMenu()
    {
        F3.setVisible(true);
    }
    public void PrivateChat()
    {
        F4.setVisible(true);
    }
    public void HomeForm()
    {
        F5.setVisible(true);
    
    }
    
    public void SendMsg(String msg) throws IOException
    {
        
        c.SendMsg(msg);
    
    }
    
    public void ShowPubMsg(String msg)
    {
        F2.ShowMsg(msg);
        
    }
    public boolean Login(String username,String password) throws IOException
    {
            
        return c.login(username,password);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new gui().setVisible(false);
                    
                } catch (IOException ex) {
                    Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
